# -*- coding: utf-8 -*-
"""MLinpython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/EmmanuelNworie/ML/blob/main/MLinpython.ipynb
"""

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt



"""Load the Titanic data"""

url = "https://raw.githubusercontent.com/eclarson/DataMiningNotebooks/master/data/titanic.csv"
#print('Pandas:', pd._version_)
#print('Numpy:', np._version_)
df = pd.read_csv(url)
df.head()

"""Group by Class"""

df.describe()

"""NEW TOPIC

Dataset Overview and Purpose

The Telco Customer Churn dataset represents customers of a telecommunications company and captures information about their demographics, services subscribed, billing details, and contractual characteristics. The dataset was originally collected to help the company understand why customers leave (churn) and to support the design of customer retention strategies.

Customer churn is a major business concern in the telecom industry because acquiring new customers is significantly more expensive than retaining existing ones. By analyzing historical customer behavior, telecom providers aim to predict which customers are at risk of leaving and intervene proactively.

Prediction Task

The prediction task is binary classification:

Predict whether a customer will churn (Yes) or not (No).

The target variable is:

Churn ∈ {Yes, No}

Stakeholders and Usefulness

Third parties interested in this prediction include:

Marketing teams (to target retention campaigns)

Customer support departments (to prioritize high-risk customers)

Business strategists (to optimize pricing, contracts, and service bundles)
"""

# Core
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

# Dimensionality Reduction
import umap.umap_ as umap

import kagglehub
import os
# Download latest version
path = kagglehub.dataset_download("blastchar/telco-customer-churn")

print("Path to dataset files:", path)

file_name = 'WA_Fn-UseC_-Telco-Customer-Churn.csv'
full_file_path = os.path.join(path, file_name)
df = pd.read_csv(full_file_path)
print('Dataset loaded into a DataFrame successfully.')
    # Display the first few rows to verify
df.head()

df.describe()

df.isna().sum()

df['TotalCharges'].value_counts().head()

df.loc[df['TotalCharges'] == " ", ['customerID', 'tenure', 'TotalCharges']]

df.head()

df.info()

"""Missing Data Visualization"""

sns.heatmap(df.isna(), cbar=False)
plt.title("Missing Data Heatmap")

"""This visualization confirms that missingness is isolated to TotalCharges and does not follow a complex missingness pattern.

Basic Feature Distributions

Plot 1: Churn Distribution (Categorical)
Insight: The dataset is moderately imbalanced, with fewer churners than non-churners.
"""

sns.countplot(x='Churn', data=df)

"""Plot 2: Tenure Distribution

Insight: Many customers churn early, while long-tenure customers are more stable.
"""

sns.histplot(df['tenure'], bins=30, kde=True)

sns.histplot(
    df['tenure'],
    bins=12,          # e.g. 12 bins = 6-month intervals
    kde=True
)

plt.xlabel("Tenure (months)")
plt.ylabel("Number of Customers")
plt.title("Histogram of Customer Tenure")
plt.show()

"""Plot 3: Monthly Charges
Insight: Customers who churn tend to have higher monthly charges.
"""

sns.boxplot(x='Churn', y='MonthlyCharges', data=df)

"""Plot 4: Total Charges

Insight: Churners generally accumulate lower total charges due to shorter tenure.
"""

sns.violinplot(x='Churn', y='TotalCharges', data=df)

"""Plot 5: Contract Type (Categorical)

Insight: Month-to-month contracts are strongly associated with churn.
"""

sns.countplot(x='Contract', hue='Churn', data=df)

# Encode categorical variables for correlation analysis
from sklearn.preprocessing import LabelEncoder

corr_df = df.copy()

# Label encode object columns EXCEPT tenure_group
for col in corr_df.select_dtypes(include='object').columns:
    if col != 'tenure_group':
        corr_df[col] = LabelEncoder().fit_transform(corr_df[col])

# Explicit ordinal encoding for tenure_group
tenure_order = ['0-12', '13-24', '25-36', '37-48', '49-60', '61-72']
corr_df['tenure_group'] = pd.Categorical(
    corr_df['tenure_group'],
    categories=tenure_order,
    ordered=True
).codes

# Compute Spearman correlation
spearman_corr = corr_df.corr(method='spearman')

plt.figure(figsize=(14,10))
sns.heatmap(spearman_corr, cmap='coolwarm', center=0)
plt.title("Spearman Correlation Heatmap")
plt.show()

"""Correlation with the Target (Churn)

Looking at the last row/column (Churn):

Strong negative correlation with tenure (~ -0.35)

Longer-tenure customers are less likely to churn

Early months are critical for retention; this matches business intuition

Moderate positive correlation with MonthlyCharges (~ +0.19)

Customers with higher monthly charges are slightly more likely to churn

Suggests price sensitivity influences churn behavior

Weak or negative correlations with some service-related features

TechSupport, DeviceProtection, OnlineSecurity show slight negative correlations (~ -0.1 to -0.15)

Customers with these services are less likely to churn, indicating added value reduces churn

Contract-related correlation

Contract codes (encoded numerically) show a negative correlation with Churn

Month-to-month contracts (low numeric code) → higher churn

Longer-term contracts → lower churn

PaperlessBilling / PaymentMethod

Small positive correlation with Churn, but relatively weak (~ +0.1)

Paperless billing slightly increases churn, possibly reflecting younger or less engaged customers

3.2 Exploratory Questions
Question 1: Does contract type influence churn?

Visualization: Contract vs Churn countplot

Interpretation:

Month-to-month customers churn significantly more

Long-term contracts act as a retention mechanism


Question 2: Do higher monthly charges increase churn risk?

Visualization: Boxplot of MonthlyCharges by Churn

Interpretation:

Churners exhibit higher median monthly charges

Pricing sensitivity is a likely churn driver


Question 3: How does tenure interact with churn?

Visualization:

sns.kdeplot(data=df, x='tenure', hue='Churn', common_norm=False)

Interpretation:

Churn probability is highest in early months

Surviving customers tend to stay long-term
"""

sns.kdeplot(data=df, x='tenure', hue='Churn', common_norm=False)

"""3.3 Interactive Visualizations (Plotly)

Interactive visualizations allow deeper exploration of patterns by enabling zooming, hovering, and filtering. This is especially useful for stakeholders who are not technical experts.


Interactive Plot 1: Monthly Charges vs Tenure Colored by Churn

Insight:

Churners cluster heavily in the low-tenure, high-monthly-charge region

Long-tenure customers show greater pricing tolerance
"""

import plotly.express as px


fig = px.scatter(
df,
x='tenure',
y='MonthlyCharges',
color='Churn',
title='Tenure vs Monthly Charges (Colored by Churn)',
opacity=0.6
)
fig.show()

"""Interactive Plot 2: Churn Rate by Contract Type
Insight:

Fiber optic customers pay higher charges and churn more frequently

DSL customers show more stable retention behavior
"""

fig = px.violin(
df,
x='InternetService',
y='MonthlyCharges',
color='Churn',
box=True,
points='all',
title='Monthly Charges Distribution by Internet Service'
)
fig.show()

"""4. Additional Analysis (Graduate Level)
Dimensionality Reduction with UMAP

UMAP (Uniform Manifold Approximation and Projection) is a nonlinear dimensionality reduction technique that:

Preserves both local and global structure

Is well suited for mixed-type, high-dimensional data

Interpretation:

Churners cluster distinctly in certain regions

Indicates strong separability in feature space
"""

from umap import UMAP
from sklearn.preprocessing import StandardScaler


X = df.drop(columns=['Churn'])
X_encoded = pd.get_dummies(X, drop_first=True)
X_scaled = StandardScaler().fit_transform(X_encoded)


umap = UMAP(n_components=2, random_state=42)
X_umap = umap.fit_transform(X_scaled)

plt.scatter(X_umap[:,0], X_umap[:,1], c=(df['Churn']=='Yes'))
plt.title("UMAP Projection of Telco Customers")

"""5. Conclusion

This exploratory analysis demonstrates that:

The dataset is clean, structured, and suitable for classification

Churn is strongly influenced by tenure, contract type, and monthly charges

Missing data is minimal and explainable

UMAP reveals meaningful latent structure supporting predictive modeling

The analysis provides a strong foundation for downstream machine learning models aimed at churn prediction.
"""